version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "06:00"
    commit-message:
      prefix: "ci"
      include: "scope"
