version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          day: "saturday"
          interval: "weekly"
          time: "06:38"
          timezone: "America/Toronto"
      commit-message:
          prefix: "ci: "
          include: "scope"
      open-pull-requests-limit: 10
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          day: "saturday"
          interval: "weekly"
          time: "05:38"
          timezone: "America/Toronto"
      commit-message:
          prefix: "ci: "
          include: "scope"
