ci:
  autofix_commit_msg: "ci(pre-commit): auto fix code"
  autofix_prs: true
  autoupdate_commit_msg: "ci(pre-commit): update pre-commit dependencies"
  autoupdate_schedule: monthly

minimum_pre_commit_version: 4.5.0
default_language_version:
  python: python3.14
default_stages: [pre-commit]
default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.8
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
