[tool.poetry]
name = "Audiobooks"
version = "0.7.1"
description = "My audiobook library program."
authors = ["Robert Poulin <poulin.robert@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/RLPoulin/Audiobooks"

[tool.poetry.dependencies]
python = "^3.10.0"
flask = "^2.0.3"
flask-sqlalchemy = "^2.5.1"
rich = "^12.0.0"
sqlalchemy = "^1.4.32"
titlecase = "^2.3"

[tool.poetry.dev-dependencies]
commitizen = "^2.21.2"
pre-commit = "^2.17.0"
sqlalchemy2-stubs = "^0.0.2a20"


[tool.commitizen]
name = "cz_conventional_commits"
version = "0.7.1"
version_files = ["pyproject.toml:version"]

tag_format = "v$version"
update_changelog_on_bump = true
changelog_incremental = false


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
