[tool.poetry]
name = "Audiobooks"
version = "0.11.2"
description = "My audiobook library program."
authors = ["Robert Poulin <poulin.robert@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/RLPoulin/Audiobooks"

[tool.poetry.scripts]
audiobooks = "audiobooks.__main__:main"

[tool.poetry.dependencies]
python = "^3.10.0"
environs = "^9.5.0"
flask = "^2.2.3"
flask-caching = "^2.0.2"
flask-sqlalchemy = "^3.0.3"
rich = "^13.3.2"
sqlalchemy = "^2.0.7"
titlecase = "^2.4"

[tool.poetry.dev-dependencies]
commitizen = "^2.42.1"
pre-commit = "^3.2.1"
pytest = "^7.2.2"
pytest-cov = "^4.0.0"
pytest-flask = "^1.2.0"
pytest-flask-sqlalchemy = "^1.1.0"


[tool.black]
line-length = 88
target-version = ["py310", "py311"]
preview = true


[tool.commitizen]
name = "cz_conventional_commits"
version = "0.11.2"
version_files = ["pyproject.toml:version", "audiobooks/__init__.py"]
tag_format = "v$version"
update_changelog_on_bump = true
changelog_incremental = false


[tool.isort]
profile = "black"
src_paths = ["audiobooks", "tests"]
lines_before_imports = 1
lines_after_imports = 2
color_output = true


[tool.pytest.ini_options]
addopts = "--cov --cov-report=term --cov-report=html"
log_auto_indent = true
log_cli = true
log_cli_level = "WARNING"
testpaths = ["tests"]
usefixtures = ["app", "test_db"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
