[tool.poetry]
name = "Audiobooks"
version = "0.7.0"
description = "My audiobook library program."
authors = ["Robert Poulin <poulin.robert@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/RLPoulin/Audiobooks"

[tool.poetry.dependencies]
python = "^3.10.0"
flask = "^2.0.2"
flask-sqlalchemy = "^2.5.1"
rich = "^10.16.1"
sqlalchemy = "^1.4.28"
titlecase = "^2.3"

[tool.poetry.dev-dependencies]
commitizen = "^2.20.3"
pre-commit = "^2.16.0"


[tool.commitizen]
name = "cz_conventional_commits"
version = "0.7.0"
version_files = [
    "pyproject.toml:version"
]

tag_format = "v$version"
update_changelog_on_bump = true
changelog_incremental = false


[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.idea
  | \.mypy_cache
  | \.venv
  | __pycache__
  | build
  | dist
)/
'''


[tool.isort]
profile = "black"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
