[tool.poetry]
name = "Audiobooks"
version = "0.11.1"
description = "My audiobook library program."
authors = ["Robert Poulin <poulin.robert@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/RLPoulin/Audiobooks"

[tool.poetry.scripts]
audiobooks = "audiobooks.__main__:main"

[tool.poetry.dependencies]
python = "^3.9.0"
environs = "^9.5.0"
flask = "^2.1.2"
flask-caching = "^2.0.0"
flask-sqlalchemy = "^2.5.1"
rich = "^12.5.1"
sqlalchemy = "^1.4.39"
titlecase = "^2.3"

[tool.poetry.dev-dependencies]
commitizen = "^2.29.0"
pre-commit = "^2.20.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-flask = "^1.2.0"
pytest-flask-sqlalchemy = "^1.1.0"


[tool.black]
line-length = 88
target-version = ["py39", "py310"]
preview = true


[tool.commitizen]
name = "cz_conventional_commits"
version = "0.11.1"
version_files = ["pyproject.toml:version", "audiobooks/__init__.py"]
tag_format = "v$version"
update_changelog_on_bump = true
changelog_incremental = false


[tool.isort]
profile = "black"
src_paths = ["audiobooks", "tests"]
lines_before_imports = 1
lines_after_imports = 2
color_output = true



[tool.pytest.ini_options]
addopts = "--cov --cov-report=term --cov-report=html"
log_auto_indent = true
log_cli = true
log_cli_level = "WARNING"
testpaths = ["tests"]
usefixtures = ["app", "test_db"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
