[tool.poetry]
name = "Audiobooks"
version = "0.5.1"
description = "My audiobook library program."
authors = ["Robert Poulin <poulin.robert@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/RLPoulin/Audiobooks"

[tool.poetry.dependencies]
python = "^3.9.0"
flask = "^1.1.4"
flask-sqlalchemy = "^2.5.1"
sqlalchemy = "^1.4.1"
titlecase = "^2.0.0"

[tool.poetry.dev-dependencies]
colorama = "^0.4.4"
commitizen = "^2.16.0"
flakehell = "^0.9.0"
ipython = "^7.21.0"
mypy = "^0.812"
pre-commit = "^2.11.0"
pretty-errors = "^1.2.19"
sqlalchemy-stubs = "^0.4"
wemake-python-styleguide = "^0.15.2"


[tool.commitizen]
name = "cz_conventional_commits"
version = "0.5.1"
version_files = [
    "pyproject.toml:version"
]

tag_format = "v$version"
update_changelog_on_bump = true
changelog_incremental = false


[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.idea
  | \.mypy_cache
  | \.venv
  | __pycache__
  | build
  | dist
)/
'''


[tool.isort]
profile = "black"


[tool.flakehell]
exclude = [
    ".eggs",
    ".git",
    ".mypy_cache",
    ".venv",
    "__pycache__"
]
format = "grouped"
show_source = true
statistics = false
doctests = true
enable_extensions = "G"

accept_encodings = "utf-8"
max_complexity = 6
max_line_length = 88

[tool.flakehell.plugins]
"flake8-*" = ["+*"]
flake8-commas = ["-*"]
flake8-darglint = ["-*"]  # enable when docstrings are mostly done
flake8-docstrings = ["+*", "-D105"]
flake8-quotes = ["-*"]
mccabe = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*", "-W503"]
pyflakes = ["+*"]
pylint = ["+*"]
wemake-python-styleguide = ["+*", "-WPS305", "-WPS323"]

[tool.flakehell.exceptions."audiobooks/models.py"]
wemake-python-styleguide = ["-WPS601"]

[tool.flakehell.exceptions."audiobooks/db_tests.py"]
wemake-python-styleguide = ["-WPS226", "-WPS421", "-WPS432"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
