# Setup uv and python.
# See https://docs.astral.sh/uv/guides/integration/github/

name: Setup Python
description: Install python and setup environment.
inputs:
  python-version:
    description: Python version to install.
    required: false
    default: "3.11"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: true
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock

    - name: Install Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Sync uv environment
      run: uv sync --dev --no-editable --frozen
      shell: bash
