# Setup python and poetry.
# See https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages

name: Setup Poetry
description: Setup python and poetry environment.
inputs:
  python-version:
    description: Python version to install.
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      id: poetry_install
      run: |
        # Install Poetry
        echo
        echo "::group:: ★ Install poetry"
        pipx install poetry
        echo "::endgroup::"
        echo
      shell: bash

    - name: Setup python ${{ inputs.python-version }}
      id: python_setup
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        architecture: "x64"
        cache: "poetry"
        check-latest: true

    - name: Setup poetry
      id: poetry_setup
      run: |
        # Setup Poetry
        echo
        echo "::group:: ★ Update pip version"
        poetry run python -m pip install -U pip
        echo "::endgroup::"
        echo "::group:: ★ Install poetry environment"
        poetry install --no-interaction --with test
        echo "::endgroup::"
        echo "::group:: ★ Poetry environment information"
        poetry env info
        echo "### Poetry Environment" >> $GITHUB_STEP_SUMMARY
        poetry env info >> $GITHUB_STEP_SUMMARY
        echo "::endgroup::"
        echo
      shell: bash
