# Setup python and poetry.
# See https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages

name: Setup Poetry
description: Setup python and poetry environment.
inputs:
  python-version:
    description: Python version to install.
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    # Setup Poetry
    - name: Install poetry
      id: poetry_install
      run: |
        echo "::group::Install Poetry"
        pipx install poetry
        echo "::endgroup::"
      shell: bash

    # Setup Python
    - run: echo "::group::Setup Python"
      shell: bash
    - name: Setup python ${{ inputs.python-version }}
      id: python_setup
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        architecture: "x64"
        cache: poetry
    - run: echo "::endgroup::"
      shell: bash

    # Setup Poetry
    - name: Setup poetry
      id: poetry_setup
      run: |
        echo "::group::Setup Poetry Environment"
        echo "::group::Update pip and setuptools"
        poetry run python -m pip install -U pip setuptools
        echo "::endgroup::"
        echo "::group::Install poetry environment"
        poetry install --no-interaction
        echo "::endgroup::"
        echo "::group::Poetry environment information"
        poetry env info
        echo "::endgroup::"
        echo "### Poetry Environment" >> $GITHUB_STEP_SUMMARY
        poetry env info >> $GITHUB_STEP_SUMMARY
        echo "::endgroup::"
      shell: bash
