# Setup python and poetry.
# See https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages

name: Setup Poetry
description: Setup python and poetry environment.
inputs:
  python-version:
    description: Python version to install.
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      id: poetry_install
      run: pipx install poetry
      shell: bash

    - name: Setup python ${{ inputs.python-version }}
      id: python_setup
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        architecture: "x64"
        cache: poetry

    - name: Setup poetry
      id: poetry_setup
      run: |
        # Setup poetry
        poetry install --no-interaction
        echo "::group::Poetry environment information"
        poetry env info
        echo "::endgroup::"
        echo "### Poetry Environment" >> $GITHUB_STEP_SUMMARY
        poetry env info >> $GITHUB_STEP_SUMMARY
      shell: bash
