# Will pass required checks if there's no relevant paths.

name: Approve Skipped Chekcs
on:
  pull_request:
    paths-ignore:
      - "audiobooks/**"
      - "tests/**"
      - "poetry.lock"

jobs:
  tests:
    name: "Tests with Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10"]

    steps:
      - run: 'echo "Check not required." '

  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "Check not required." '
