# Reusable workflow to setup python and poetry.

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        default: "3.10"
        type: string
      os:
        required: false
        default: ubuntu-latest
        type: string

jobs:
  setup:
    name: Setup Poetry for Python ${{ input.python-version }}
    runs-on: ${{ input.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Setup python ${{ input.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ input.python-version }}
          architecture: "x64"
          cache: poetry

      - name: Setup poetry
        run: poetry install --no-interaction

      - name: Show poetry environment information
        run: poetry env info
