# Run tests on supported python versions on Ubuntu and Windows.

name: Tests
on: push

jobs:
  tests:
    name: "Tests with Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.14"]
        os: ["ubuntu-latest", windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests
